version: "3"

services:
  canasta-scores:
    container_name: canasta-scores
    build:
      context: .
      args:
        GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://canasta_dev:canasta_dev@db-dev:5432/canasta_dev
      - SWAGGER=ENABLED
      - NODE_ENV=development
    ports:
      - "4000:4000"
      - "9229:9229"
    depends_on:
      - db-dev
    volumes:
      - "./logs:/root/.npm/_logs"
      - "./logs-node:/home/node/.npm/_logs"
      - "./src:/usr/src/app/src"
      - "./coverage:/usr/src/app/coverage"
      - "./tsconfig.json:/usr/src/app/tsconfig.json"
      - "./jest.config.js:/usr/src/app/jest.config.js"
      - ".env:/usr/src/app/.env"
      - "./var:/usr/app/var"
      - "./.eslintignore:/usr/src/app/.eslintignore"
      - "./.eslintrc:/usr/src/app/.eslintrc"
      - "./swagger:/usr/src/app/swagger"
      - "./test:/usr/src/app/test"
    command: ["npm", "run", "watch-debug"]

  db-dev:
    image: postgres:9.6.6-alpine
    read_only: true
    environment:
      - POSTGRES_USER=canasta_dev
      - POSTGRES_PASSWORD=canasta_dev
      - POSTGRES_DB=canasta_dev
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - db-dev:/var/lib/pgsql/9.6/data:rw,cached
      - ./postgres:/docker-entrypoint-initdb.d/
    expose:
      - "5432"
    ports:
      - "127.0.0.1:1668:5432"

volumes:
  db-dev:
    driver: local